# Generated by Django 2.1.5 on 2019-03-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='conform_pass',
            new_name='confirm_pass',
        ),
    ]
